### PR TITLE
improvement of few words and format

### PR DESCRIPTION
**Pull request by vrkansagara**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi, thanks for the PR.
Please rebase, so only your new commits are present

**Comment by vrkansagara** [comment]
Hello @TomasVotruba  I tried but I can not able to the right way. Can you please guide me how to do this.

**Comment by TomasVotruba** [comment]
Hi, this might help https://stackoverflow.com/questions/7929369/how-to-rebase-local-branch-onto-remote-master

**Comment by vrkansagara** [comment]
Closing this PR against #14

**Pull request closed without merging**
